// LANGUAGE
export const SET_LANGUAGE = 'SET_LANGUAGE';
// AUTHENTICATION
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const GET_TOKEN = 'GET_TOKEN';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
// ERRORS
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
// EVENTS
export const FETCHING_EVENTS = 'FETCHING EVENTS';
export const GET_EVENTS = 'GET_EVENTS';
export const SELECT_EVENT = 'SELECT_EVENT';
export const CREATING_EVENT = 'CREATING_EVENT';
export const CREATE_EVENT = 'CREATE_EVENT';
// CONTACTS
export const FETCHING_CONTACTS = 'FETCHING_CONTACTS';
export const ADDING_NEW_CONTACT = 'ADDING_NEW_CONTACT';
export const INVITING_CONTACTS = 'INVITING_CONTACTS';
export const GET_CONTACTS = 'GET_CONTACTS';
export const ADD_CONTACT = 'ADD_CONTACT';
export const INVITE_CONTACTS = 'INVITE_CONTACTS';
export const INVITED_CONTACTS = 'INVITED_CONTACTS';
// ORDER
export const FETCHING_FOOD = 'FETCHING_FOOD';
export const FETCHING_DRINKS = 'FETCHING_DRINKS';
export const GET_FOOD = 'GET_FOOD';
export const GET_DRINKS = 'GET_DRINKS';
export const SELECT_FOOD = 'SELECT_FOOD';
export const SELECT_DRINKS = 'SELECT_DRINKS';
// INGREDIENTS
export const FETCHING_INGREDIENTS = 'FETCHING_INGREDIENTS';
export const GET_INGREDIENTS = 'GET_INGREDIENTS';
export const EMAILING_MISSING_INGREDIENTS = 'EMAILING_MISSING_INGREDIENTS';
export const SET_MISSING_INGREDIENTS = 'SET_MISSING_INGREDIENTS';
export const EMAIL_SENT = 'EMAIL_SENT';
// RECPE
export const FETCHING_RECIPES = 'FETCING_RECIPES';
export const GET_RECIPES = 'GET_RECIPES';
export const TOGGLE_ALEXA_MODE = 'TOGGLE_ALEXA_MODE';
// QUIZ
export const CREATING_QUIZ = 'CREATING_QUIZ';
export const CREATE_QUIZ = 'CREATE_QUIZ';
export const GUEST_USERNAME = 'GUEST_USERNAME';
export const JOINING_QUIZ = 'JOINING_QUIZ';
export const JOIN_QUIZ = 'JOIN_QUIZ';
export const SET_CATEGORY = 'SET_CATEGORY';
export const FETCHING_QUESTION = 'FETCHING_QUESTION';
export const GET_QUESTION = 'GET_QUESTION';
export const ANSWERING_QUESTION = 'ANSWERING_QUESTION';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const GET_ANSWERS = 'GET_ANSWERS';
export const VOTING_FOR_ANSWER = 'VOTING_FOR_ANSWER';
export const GET_VOTE = 'GET_VOTE';
export const GET_VOTES = 'GET_VOTES';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const QUIZ_ENDED = 'QUIZ_ENDED';
// ECHO
export const CONNECTING = 'CONNECTING';
export const CONNECTED = 'CONNECTED';
export const DISCONNECTED = 'DISCONNECTED';
export const CONNECTION_FAILED = 'CONNECTION_FAILED';
export const GET_NOTIFICATION = 'GET_NOTIFICATION';
export const USER_CONNECTED = 'USER_CONNECTED';
export const USER_DISCONNECTED = 'USER_DISCONNECTED';
